language: php
dist: xenial

sudo: required

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  mariadb: '10.0'
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master
  - DB=mariadb MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - composer require --dev dmore/behat-chrome-extension
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &

install:
  - moodle-plugin-ci install

script:
  - phpunit "provider_testcase" privacy/tests/provider_test.php --colors="always"
  - moodle-plugin-ci phplint vendor/bin/
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile chrome
  - moodle-plugin-ci behat
  